## ADD service filebrowser for edit config traefik

# ENV required
# --------------------------------------------
# SERVICE_NAME=filebrowser4traefik
# DOMAIN=localhost
# BASE_URL=/filebrowser4traefik
# VOLUME_MOUNT=/etc/traefik
# PUID=1000
# PGID=1000
# --------------------------------------------
# END ENV
version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    environment:
      TZ: Asia/Bangkok
      PUID: ${PUID}
      PGID: ${PGID}
    # default user: admin:admin
    command: --baseurl "${BASE_URL}"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.tls=true"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web,websecure"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`) && PathPrefix(`${BASE_URL}`)"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
    networks:
      - proxy
    volumes:
      - ${VOLUME_MOUNT}:/srv
      - ${VOLUME_MOUNT}:/database/filebrowser.db
      - /var/log/traefik:/srv/log/traefik

networks:
  proxy:
    external: true
