http:
  routers:
    __SERVICE__:
      rule: Host(`__DOMAIN__`) && PathPrefix(`__PATHPREFIX__`)
      service: portainer
      entryPoints:
        - web
        - websecure
      tls: true

  services:
    __SERVICE__:
      loadBalancer:
        servers:
          - url: "http://__SERVICE__"
