global:
    checkNewVersion: false
    sendAnonymousUsage: false

serversTransport:
    insecureSkipVerify: true

entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: ":443"
    dashboard:
        address: ":8080"
    metrics:
        address: :8082

providers:
    docker:
        watch: true
        network: proxy
        swarmMode: true
        swarmModeRefreshSeconds: 30s
        httpClientTimeout: 60s
        exposedByDefault: false
    file:
        directory: /etc/traefik/configs
        watch: true

api:
    insecure: false
    dashboard: true

ping:
    manualRouting: true

metrics:
    prometheus:
        entryPoint: metrics

log:
    level: INFO
    format: common
accessLog:
    filePath: /var/log/traefik/access.log
    format: json
    bufferingSize: 100
    fields:
        defaultMode: keep
        names:
            StartUTC: drop
