http:
  routers:
    ping_router:
      rule: Host(`__DOMAIN__`) && Path(`/ping`)
      service: ping@internal
      entryPoints:
        - web
        - websecure
        - dashboard
      tls: true

    dashboard_router:
      rule: Host(`__DOMAIN__`) && PathPrefix(`/dashboard`, `/api`)
      service: api@internal
      entryPoints:
        - dashboard
      middlewares:
        - auth_dashboard
      tls: true

  middlewares:
    auth_dashboard:
      basicAuth:
        users:
          - "admin:$2y$10$AZnZK/lLh91Byw/.uzfPUeHH7LJHC.Pv48uuyUPGmgU/kQ5Vy6.9u" # admin:admin

