version: "3.0"

networks:
  proxy:
    external: true
services:
  traefik:
    image: traefik:2.8
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 9000:9000 # for portainer port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/:/traefic/configs
      - ./certs/:/certs
      - /var/log/traefik/:/var/log/traefik/
    networks:
      - proxy
    restart: unless-stopped
    command:
      # Expose Endport listener
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dashboard.address=:8080"
      - "--entrypoints.portainer.address=:9000"


      - "--global.sendAnonymousUsage"
      - "--global.checkNewVersion"
      - "--serverstransport.insecureskipverify=true"
      # Operations
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--ping"
      - "--ping.manualrouting=true"

      # Provider
      - "--providers.docker"
      - "--providers.docker.swarmmode=false"
      - "--providers.docker.network=proxy"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.httpclienttimeout=3600"
      - "--providers.file.directory=/traefic/configs"
      - "--providers.file.watch=true"

      # logs
      - "--log.level=DEBUG"
      - "--accesslog"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.filepath=/var/log/traefik/access.log"




    labels:
      - "traefik.enable=true"

  

