# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  DIR_CERTS: ./certs

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  new-network:
    cmds:
      - cmd: docker network create --attachable --driver=overlay proxy
        ignore_error: true
      # - cmd: docker network create --attachable --driver=bridge proxy
      #   ignore_error: true

  rm-network:
    cmds:
      - cmd: docker network rm proxy
        ignore_error: true
