# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  DIR_CERTS: ./certs

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run-stack:
    cmds:
      - cmd: docker network create --driver=overlay proxy
        ignore_error: true
      - docker stack deploy -c docker-stack.yaml traefik
  run-compose:
    cmds:
      - cmd: docker network create --driver=bridge proxy
        ignore_error: true
      - docker-compose up -d
