# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /certs/cert.pem
#         keyFile: /certs/key.pem

http:
  routers:
    ping_router:
      rule: Host(`__DOMAIN__`) && Path(`/ping`)
      service: ping@internal
      entryPoints:
        - dashboard
      tls: true

    dashboard_router:
      rule: Host(`__DOMAIN__`)
      service: api@internal
      entryPoints:
        - dashboard
      tls: true
