http:
  routers:
    portainer:
      rule: Host(`__DOMAIN__`) && PathPrefix(`/portainer`)

      service: portainer
      entryPoints:
        - web
        - websecure
      tls: true
      middlewares:
        - portainer-stripprefix
  middlewares:
    portainer-stripprefix:
      stripprefix:
        prefixes:
          - /portainer

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://portainer:9000"
