http:
  routers:
    portainer:
      rule: Host(`__DOMAIN__`)
      service: portainer
      middleware:
        - portainer-stripprefix
      entryPoints:
        - web
        - websecure
      tls: true

  middleware:
    portainer-stripprefix:
      stripprefix:
        prefixes:
          - /portainer

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
