version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.14.1
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    # ports:
    #   - "9000:9000"
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # Frontend
        - "traefik.enable=true"
        #  Portainer UI
        - "traefik.http.routers.portainer.entrypoints=portainer"
        - "traefik.http.routers.portainer.rule=PathPrefix(`/`)"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  portainer-agent:
    image: portainer/agent:2.11.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    environment:
      - TZ=Asia/Bangkok
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  agent_network:
    driver: overlay
    attachable: true
  proxy:
    external: true